/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118655-g696ea1c223-20250306"
#endif /* AVUTIL_FFVERSION_H */
